### ISSUE TITLE
Great package

### ISSUE THREAD

**Issue by rpaguirre** [tudoanh/python-facebook-bot#1]
Would love to be able to install this package through pip. It would be useful to look at the pip documentation to get this package to do something like:

import getfbevents

c = getfbevents.losangeles(2017/04/18-2017/05/2018)

print(c)

fbevent, location, address, date

**Comment by tudoanh** [comment]
Thank you. A installable package seem like good idea.

I can do it, but I must consider is that worth trying to do, because Facebook do not allow to search events direct way anymore, we need to scan all places in a circle, then check if any of them have event to return or not, so it'll take a lot of time to crawl.

**Comment by tudoanh** [comment]
@rpaguirre Updated. Run `pip install python-facebook-bot` to install this package. I'll update docs soon.
